name: xzchat
description: "All Secure Chat."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.0
  provider: ^6.1.2
  uuid: ^4.5.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  file_picker: ^10.2.0
  permission_handler: ^12.0.1
  encrypt: ^5.0.3
  firebase_storage: ^13.0.0
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - images/
